### ISSUE TITLE
Email Authentication

### ISSUE THREAD

**Issue by laurie-y** [classifiedz/classifiedz.github.io#112]
Users should be sent an email to verify that the email address they are using to register for an account exists.

**Comment by neqqash** [comment]
Great idea! gives our customers the impression that our site is secure

**Comment by kevcamel** [comment]
Did some research and founds this:
https://blog.damirmiladinov.com/laravel/laravel-5.2-email-verification-with-activation-code.html#.Wd9y3ytE2Ec

**Comment by neqqash** [comment]
I did some background research on this, it has something to do with the database as well. I will sit down with @BrandonBalala and will look over it together
