### ISSUE TITLE
Omit asking users to include a special character in password? 

### ISSUE THREAD

**Issue by neqqash** [classifiedz/classifiedz.github.io#115]
I think we should only enforce users to have a capital letter and numbers, special characters makes it too hard, in my opinion. What do you guys think?

**Comment by Swallow666** [comment]
Agree with you.

**Comment by laurie-y** [comment]
It's becoming a more common requirement these days because it makes accounts more secure

**Comment by BrandonBalala** [comment]
I remember our TA telling us to add more validations, including the special character constraint.

**Comment by neqqash** [comment]
I just recall him saying to enforce users to have numbers and capital letters, however, it does make the passwords more secure which is essentially what we want our customers to feel.
