### ISSUE TITLE
Add Favicon to website tab

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#116]
Add a favicon to the tab, so our website looks less ghetto.
Ideas:
- Magnifying Glass
- Different colors ?
What do you guys think ? @rami186 @BrandonBalala @laurie-y  @monnyy @neqqash @HanGao2333 @Swallow666

**Comment by neqqash** [comment]
Sounds like a great idea, makes our website look more professional.  Not too sure about the magnifying glass, and cant think of one on the top of my head. But once i do i'll note it down ASAP

**Comment by kevcamel** [comment]
<img width="250" alt="favicon" src="https://user-images.githubusercontent.com/16027312/31310084-b1c648f0-ab5f-11e7-9712-2cd5b5e000ce.png">
what do you guys think?

**Comment by BrandonBalala** [comment]
Yea looks fine by me.  Good color and very simple.  This is a good logo because it is distinguishable even at a small dimension

**Comment by Swallow666** [comment]
Good idea, but I don't think black color is perfect for blue navbar. Or may be we can change navbar to black-white scheme.

**Comment by kevcamel** [comment]
@Swallow666 What color would you prefer?
<img width="563" alt="screen shot 2017-10-11 at 11 39 40 pm" src="https://user-images.githubusercontent.com/16027312/31478388-023dad88-aede-11e7-941a-e773eb7d4e0e.png">

**Comment by Swallow666** [comment]
@kcamcam Actually, I prefer all black like apple website.

**Comment by kevcamel** [comment]
like the picture i just sent?

**Comment by Swallow666** [comment]
ya I think we can vote for this

**Comment by monnyy** [comment]
I found a way through which we can create a favicon from a jpg file(photo)

**Comment by kevcamel** [comment]
the image I uploaded up top is a PNG, which is correct format for a favicon
`<link rel="shortcut icon" type="img/png" href="img/favicon.png">` is th way to do it.

**Comment by laurie-y** [comment]
I think the magnifying glass looks good. It's simple and easy on the eyes

**Comment by kevcamel** [comment]
so much action on this issue 😂
