### ISSUE TITLE
Enhancement on the ClassifiedZ logo

### ISSUE THREAD

**Issue by monnyy** [classifiedz/classifiedz.github.io#117]
Changing from a word logo to an iconic logo (on the navbar).
This is what I started with. I need your opinion @kcamcam @rami186 @laurie-y @Swallow666 @neqqash @BrandonBalala @HanGao2333 .
Improvements can be made on the logo(color, disposition and anything else you might want.

<img width="242" alt="screen shot 2017-10-07 at 1 34 06 pm" src="https://user-images.githubusercontent.com/25891267/31311739-adbce7e8-ab80-11e7-8a9f-2f60ec6719eb.png">

OR, this one:

<img width="175" alt="screen shot 2017-10-11 at 11 16 36 am" src="https://user-images.githubusercontent.com/25891267/31449778-da5db992-ae75-11e7-8284-7ceb5828b48d.png">

**Comment by neqqash** [comment]
No improvements needed, this logo is perfect!, it displays everything our website is about and where we are located.

**Comment by kevcamel** [comment]
Love it! Would it be possible to change the colors of the logo to match those of our website? If not we would need to change the colors of our website to match the logo. Either works tho.

If you want to implement it, you could use this:
https://v4-alpha.getbootstrap.com/components/navbar/
  `<a class="navbar-brand" href="#"><img src="img.png" width="30" height="30" alt=""></a>`

**Comment by laurie-y** [comment]
I like the first one best. I do think that the color should be changed to match the color scheme of the website though (unless we change the color scheme of the website)
