### ISSUE TITLE
Add use picture to navbar

### ISSUE THREAD

**Issue by Swallow666** [classifiedz/classifiedz.github.io#118]
After login, should user picture also shows on the navbar? Anyone give me some ideas about this. And if it is good, how can I upload user picture there (coding details)?

**Comment by Swallow666** [comment]
By clicking the user pic on navbar, page will jump to profile page also.

**Comment by kevcamel** [comment]
Personally I think it would be overkill on the navbar, too much going on. It is still a good idea none the less. 
If you would want to implement this you could use bootstrap responsive image category and add the rounder class to it as well.
https://v4-alpha.getbootstrap.com/content/images/

**Comment by neqqash** [comment]
i agree with kevin, although it is a good feature to implement, we should add that near the end which would enhance our website more.

**Comment by kevcamel** [comment]
This issue is getting a sprint 7 and gonna close it
