### ISSUE TITLE
Register - Identical password 

### ISSUE THREAD

**Issue by monnyy** [classifiedz/classifiedz.github.io#120]
Making sure the user enters identical passwords when registering

**Comment by laurie-y** [comment]
Isn't this already done?

**Comment by monnyy** [comment]
I had someone getting to register.
He typed in, 2 different password (that is password, confirm password), but the error he had was, he's missing a capital letter and special character.

**Comment by neqqash** [comment]
i think it is done, just checked it right now and it does indeed give me an error saying the password confirmation does not match.

**Comment by laurie-y** [comment]
When they tried to register, did the initial password meet the requirements? 

The password has to meet the requirements before it even checks if both passwords are the same. If the password doesn't meet the requirements then it shouldn't pass, regardless of whether or not the 2 passwords match.

**Comment by monnyy** [comment]
oh right
