### ISSUE TITLE
Burndown  Chart for Sprint 3

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#124]
we need to create a burndown chart for sprint 3, any volunteers?

**Comment by neqqash** [comment]
il be glad to tag along for this issue with you :)

**Comment by kevcamel** [comment]
I added the burndown chart to the wiki

**Comment by kevcamel** [comment]
[user stories from sprint 3](https://github.com/classifiedz/classifiedz.github.io/issues?q=is%3Aissue+milestone%3A%22Sprint+3%22+is%3Aclosed+label%3A%22User+Story%22), which are updated with hours and points. Link to [google sheets for burndown chart](https://docs.google.com/spreadsheets/d/1NoJsbVXXRKU33B8pewVWSNnjQK6LTo3X0ov_50jTBO0/edit#gid=0).
