### ISSUE TITLE
Set up Unit Tests on Travis-CI

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#126]
Set up 3-4 unit tests for database/project functionality.

**Comment by kevcamel** [comment]
- Test 1: Input data then check if its there 
- Test 2: Delete data then check if its deleted
- Test 3:  Update data then check if its been modified
- Test 4: Query database and validate results (ex query price 0-100, validate results)

**Comment by BrandonBalala** [comment]
Tests are ran with the following command:
./vendor/bin/phpunit

@kcamcam mind setting up travis so that it runs the tests when you can?  All my tests are on "unit-tests" branch.

**Comment by kevcamel** [comment]
will do

**Comment by kevcamel** [comment]
.travis.yml file update here is the output:
~~~
Starting test 'Tests\Feature\RouteResponseTest::testHomepage'.
.
Starting test 'Tests\Feature\RouteResponseTest::testNonExistentPage'.
.
Starting test 'Tests\Unit\ProductDBTest::testProductCreation'.
.
Starting test 'Tests\Unit\ProductDBTest::testProductDeletion'.
.
Starting test 'Tests\Unit\ProductDBTest::testProductUpdate'.
.
Starting test 'Tests\Unit\ProductDBTest::testProductQuery'.
.                                                              6 / 6 (100%)
Time: 337 ms, Memory: 16.00MB
OK (6 tests, 6 assertions)
The command "vendor/bin/phpunit --debug" exited with 0.
Done. Your build exited with 0.
~~~
