### ISSUE TITLE
Front End: Merge Laravel into Master Branch

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#13]
### Massive Merge
So were going to need to merge these two branches... heavy duty stuff. Like @BrandonBalala outlined in slack this is whats going to need to be done:  
- **HTML files** should now be under `/resources/views`
- **HTML files** files should now have the extension `.blade.php` instead of `.html`
- All **Assets**  should be in the `/public` folder
  - Example : any '.css, .js, etc...' files, all image files (`.png, .jpg, etc...`)
- In order to create new routes e.g `classifiedz.xyz/about` you ned to do the following:
   1. Add a new route in '/routes/web.php' file with `/about`' as the first parameter
   2. The return statement should be  `return view('anyAppropriateName');`
   3. Then create `anyAppropriateName.blade.php` which will contain all the HTML

![Merge Gif](https://media.tenor.com/images/907ca4314bc8af09f6c3ca5719d60f7e/tenor.gif)

**Comment by laurie-y** [comment]
Pull Request #14 closes this issue
