### ISSUE TITLE
Populate database with REAL mock data and pictures

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#130]
Might be a long issue to resolve, but it would be nice to have this done for the presentation.

**Comment by BrandonBalala** [comment]
I really don't feel like this is an issue.  We really don't need to have actual real data. It's not important as we will demo creating a new ad and this new ad would appear on homepage hence proving that everything works properly.  But I guess if you guys want to make up ads and gather images have fun!

**Comment by kevcamel** [comment]
I didn’t think about that, you’re right. Let’s scrap the issue and go with your suggestion

**Comment by neqqash** [comment]
i agree with Brandon, i think if we make real data it would take a really long time, as we would have to go through each category --> subcategory and manually input them. Better off showing how the website functions and that it is indeed functional
