### ISSUE TITLE
Make entire ad cards clickable

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#142]
Would this be a good idea? ant thoughts?  
I found a way to implement it, and tested it.  
`<a href="/ads/{{ $product->id }}" style="position: absolute; top: 0; left: 0; height:90%; width: 100%;"></a>`  
The height is set to 90% so that our pills are still usefull to us. This means only the first 90% of the ad from top to bottom is clickable.

**Comment by laurie-y** [comment]
I think we decided against this to try and minimize the chances of users accidentally clicking an ad

**Comment by kevcamel** [comment]
Also worth mentioning is it does remove the ability to select text on the card.

**Comment by neqqash** [comment]
yeap, we did agree on having only the ad picture and title clickable.

**Comment by kevcamel** [comment]
ayt closing this issue
