### ISSUE TITLE
Username validation required

### ISSUE THREAD

**Issue by laurie-y** [classifiedz/classifiedz.github.io#143]
When a user registers, the username needs to be checked and a message needs to show if the username has already been taken or not. Right now, if you use the same username, an error occurs.

**Comment by Swallow666** [comment]
This is an emergency issue, how could this issue be solved, php?

**Comment by kevcamel** [comment]
this might be a good start <https://stackoverflow.com/questions/31800074/checking-username-availability-in-laravel>

**Comment by BrandonBalala** [comment]
This was a simple fix i created a pull request for it!
