### ISSUE TITLE
Ads should be in "Your store" or "Profile page" ?

### ISSUE THREAD

**Issue by Swallow666** [classifiedz/classifiedz.github.io#144]
For profile_page user story, we have tasks to put user ads in profile page (also delete ads there), but I remembered we have "Your Store" button on Navbar. So do we really need to put ads in profile page, or put user ads with delete function in 'Your Store' ?

**Comment by laurie-y** [comment]
Your store and profile are essentially the same. I think we can merge the two and just put your store as profile in the dropdown

**Comment by Swallow666** [comment]
@laurie-y  hmm I think we can keep this two for now, 'profile' contains phone number, emails, etc (not including ads), meanwhile 'Your store' contains only users' ads (they can check ads posted there and delete them). 
So we should complete 'your store' in sprint 3 ?

**Comment by neqqash** [comment]
i agree with @Swallow666, best to keep profile page about the user and your store is where the ads will be.

**Comment by laurie-y** [comment]
I think it could be a good idea to have one page but display certain things depending on if it's your profile or not

**Comment by BrandonBalala** [comment]
I guess for know, we can simply have them separated and in Sprint 7 we could merge them into one.

So right now we'd have /profile where users can see/edit their profile settings, These info you don't really want everyone to see.

And then we should have /store/{user} which is publicly available to everyone which shows to others what items they are currently selling.  If you are in your own /store/{your_used_id} you should be able to edit/remove you ads.

**Comment by laurie-y** [comment]
@HanGao2333 @Swallow666 If we're having both the profile page and store page, are you two creating the store page as well? I need the page that users will go to if they're looking at a seller.

**Comment by kevcamel** [comment]
I agree with keeping them separate. Combining them and displaying limited results could be a sprint 7 issue.
