### ISSUE TITLE
The email in profile shall be different from the login email

### ISSUE THREAD

**Issue by Swallow666** [classifiedz/classifiedz.github.io#160]
Right now when u change the email in edit profile page, your login email also changes. 
The email in profile page should be an email for contacting, so when u change this email in edit profile page, your login email should stay the same.

**Comment by BrandonBalala** [comment]
I don't think this is an issue. I don't really see any platforms that have different login email and contact email. I feel this is a really odd thing to want to change?

**Comment by neqqash** [comment]
i agree. It would be unnecessary to have 2 emails, one should suffice for both login and profile.

**Comment by Swallow666** [comment]
The thing is, when u change ur contact email for others to contacting with u, the system doesn't give u a choice, then u can't use ur original registered email to login, this is weird.

**Comment by laurie-y** [comment]
The email you register with is also the email you're contacted with. So by changing your contact email, you're changing your login email as well. It makes sense that you can't login with your original email if you've changed it.

**Comment by BrandonBalala** [comment]
Ye changing email means you won't be able to login with with your registered email. That is the expected behavior

**Comment by Swallow666** [comment]
k ill close this issue
