### ISSUE TITLE
[User Story 14] Your Store

### ISSUE THREAD

**Issue by Swallow666** [classifiedz/classifiedz.github.io#161]
### Your Store

| Risk | Priority | Story Points |  
| :---: | :---: | :---: |  
| High | Medium | **8** |  

As a user (buyer), I would like to be able to see if sellers are selling other items by visiting the sellers store. I would also like to be able to contact them if I would like to purchase on their items for sale.

- [x] 7.1 Create yourStore.blade.php #??? (**0.1 Hours**)   
- [x] 7.2 Display contact information to seller #??? (**1 Hours**)  
- [x] 7.3 Display all ads specific to seller #??? (**1 Hours**)  
- [ ] 7.4 Display seller five star rating #??? (**2 Hours**)   
- [x] 7.5 Sellers can delete their ads #??? (**0.5 Hours**)   

#### Total: **4.6 Hours**

**Comment by Swallow666** [comment]
I have created yourstore.blade.php

**Comment by Swallow666** [comment]
in profile-pages branch

**Comment by kevcamel** [comment]
Dont forget to use [the template](https://github.com/classifiedz/classifiedz.github.io/wiki/%5BUser-Story%5D-Template) when creating user storeis.

**Comment by laurie-y** [comment]
So what're we doing with the Your Store/profile page now? keeping them separate? Merging them as one? Making them completely different from each other?

**Comment by kevcamel** [comment]
When a user visits a sellers page display or when a seller visits a users page display, theyre both the same:  
- Name, ads, contact info, ratings

Maybe we could just have a EDIT button somewhere on the page that only shows up if your viewing your own page, else only display page

**Comment by BrandonBalala** [comment]
Yea if seller is in his own store, he should be able to manage all his active ads. So having an edit button if viewing own page is what we should do like you said.

**Comment by laurie-y** [comment]
So we remove profile page from the drop down? Are we putting wishlist in the dropdown instead?

**Comment by BrandonBalala** [comment]
Yea we should put wishlist in the dropdown instead of having to access wishlist from the profile page.

**Comment by kevcamel** [comment]
The dropdown should have
- Edit Profile
- Wishlist
- Logout

**Comment by kevcamel** [comment]
@Swallow666 @HanGao2333 you should have issues created for each task, so that you can reference them when you commit.
Ex:
we should have an issue called  7.1 Create yourStore.blade.php #000 (0.1 Hours)
then when you commit your message should be
"Create the yourStore.blade.php view, resolves #000

**Comment by laurie-y** [comment]
## Acceptance Test
![us14](https://user-images.githubusercontent.com/31772505/32359805-d6fc5f48-c026-11e7-8498-6e26c6964297.PNG)
