### ISSUE TITLE
[User Story 13] Contacting Sellers

### ISSUE THREAD

**Issue by laurie-y** [classifiedz/classifiedz.github.io#175]
### Contact Seller
| Risk | Priority | Story Points |
| :---: | :---: | :---: | 
| Low | High | **2** |

As a user, I want to be able to contact sellers about their products that I am interested in so that I can speak to them directly for more information.

- [ ] 6.1 Create a link on ad to sellers store page #161 which will contain contact info #??? (**2 Hours**)   

#### Total: **X Hours**

**Comment by kevcamel** [comment]
Dont forget to use [the template](https://github.com/classifiedz/classifiedz.github.io/wiki/%5BUser-Story%5D-Template) when creating user storeis.

**Comment by laurie-y** [comment]
Yeah, I wasn't sure how the tasks would be broken up

**Comment by kevcamel** [comment]
We decided not to discontinue this feature.
