### ISSUE TITLE
Discussion for Past/Present/Future Issues

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#179]
## Future Issues to Create   

- [X] pagination  
- [X] 404 page  
- [X] search within category  
- [X] card functionality (email on profile page)  
- [X] Card Columns L -> R not Top to Bottom  
- [X] profile/store page merged together  
- [X] Your Store : Delete Ads  
- [X] Create Account : Email Activation Link  
- [X] User/Seller Reviews
- [X] ~Refactoring~
- [X] ~More Refactoring~
- [ ] Comments/Blog Under Ads
- [ ] tooltip popup
- [x] ~Edit Profile Change Password~

**Comment by kevcamel** [comment]
- Who wanted the tooltip and what was this for again???  @monnyy this was u right?
- Change password, lets talk advantage of being ahead and  Sprint 7 the shit out of this issue?
- Comments under ads, @rami186 what was the name of the plugin you wanted to use?

**Comment by BrandonBalala** [comment]
Yea, if they don't ask for it it let's not have a change password feature lool

**Comment by neqqash** [comment]
i think for comments under ads was crisp, and change passwords --> sprint 7.

**Comment by kevcamel** [comment]
thanks, i also found this [disqus](https://disqus.com/).
