### ISSUE TITLE
[User Story 12] Product Comment Section

### ISSUE THREAD

**Issue by BrandonBalala** [classifiedz/classifiedz.github.io#183]
### Product Comment Section
| Risk | Priority | Story Points |
| :---: | :---: | :---: | 
| Low | Low| **1** |

As a user, I want to be able to post comment or discussions on a specific ad page. This section is visible to everyone as opposed to contacting a seller.

#### Total: **1 Hour**

**Comment by kevcamel** [comment]
what happened to user story 8?

**Comment by laurie-y** [comment]
Acceptance Test
![us12](https://user-images.githubusercontent.com/31772505/32357185-cbce8652-c010-11e7-9b78-c73a66ba17ff.PNG)
