### ISSUE TITLE
[User Story 17] Prompt Before Deleting ad

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#195]
### Prompt Before Deleting ad

| Risk | Priority | Story Points |
| :---: | :---: | :---: | 
| High | Low | **2** |

As a a User when I am deleting an ad I should be prompted to confirm the deletion before it is officially deleted from the database.

- [ ] 17.1 Create popup that is triggered when delete is clicked #??? (**2 Hours**) 

#### Total: **2 Hours**

**Comment by kevcamel** [comment]
Bootstrap has a **Modal** that can serve this purpose.
https://v4-alpha.getbootstrap.com/components/modal/#examples

**Comment by laurie-y** [comment]
## Acceptance Test
![us17](https://user-images.githubusercontent.com/31772505/32921440-9985dd26-cafb-11e7-9564-50f5c0183cc5.PNG)
