### ISSUE TITLE
Add a "Add to Wishlist" button on individual ad page

### ISSUE THREAD

**Issue by BrandonBalala** [classifiedz/classifiedz.github.io#208]
![23757580_1687550491297756_629983413_o](https://user-images.githubusercontent.com/25891267/32928013-e30547b2-cb1d-11e7-8d15-2781ad64574c.jpg)

**Comment by monnyy** [comment]
![23714903_1687555234630615_1245410525_o](https://user-images.githubusercontent.com/25891267/32928297-3de09dfc-cb1f-11e7-9cfb-b0d1ca32cc16.jpg)
