### ISSUE TITLE
Clean Up Root Directory

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#209]
Clean up the all the clutter in the Github repo.
- [x] Delete **laravel-instructions-osx.md**
- [x] Delete **.env example**
- [x] Delete **DS_store**
- [x] ._composer.json
- [x]  CNAME

**Comment by kevcamel** [comment]
@BrandonBalala can you confirm/edit what can be cleaned up?

**Comment by BrandonBalala** [comment]
Remove these too
._composer.json
CNAME

**Comment by BrandonBalala** [comment]
Once you delete those files off of github, also add them to the .gitignore file

**Comment by HanGao2333** [comment]
Problem fixed
