### ISSUE TITLE
Login should direct to login or register

### ISSUE THREAD

**Issue by laurie-y** [classifiedz/classifiedz.github.io#21]
To prevent clutter in the navbar, the user should have to click login and be directed to a login page.
If they do not already have an account, they should be able to go to a registration page.

- [ ] "Don't have an account? Register Now!" **Link from login**
- [ ] "Already have an account? Sign in!" **Link from registration to bring you back to login**

**Comment by Swallow666** [comment]
for more details, we need to add hint below login button (e.g., "not register yet, click here"), so users will know where to register. This is because users usually not gonna click login if they didn't registered yet.

**Comment by neqqash** [comment]
would we be able to do the following ;

when a user goes to the page, he is directed to a login/register page right off the bat, so left hand side login, right hand side register. Once the login/register is done, the user is directed to the home page of the website

**Comment by laurie-y** [comment]
@Swallow666  A lot of sites will have just a login button and then give you the option to register if you don't already have an account (Google/YouTube, Yahoo, Bing, letgo, etc.). 

It's all visual preference honestly so it's fine either way. If we don't want to change it, we can mark this issue as invalid and close it.

**Comment by kevcamel** [comment]
@Swallow666 @laurie-y, this is a very good point and I think we should keep the issue open and solve it.
