### ISSUE TITLE
When we click checkbox of "I have read and agree to the Terms and Conditions" in edit ad page or post ad page, where the "Terms and Conditions" should be linked to?

### ISSUE THREAD

**Issue by Swallow666** [classifiedz/classifiedz.github.io#211]
It should link to which one of "Privacy Notice, Posting Policy, Sales and Refunds, Terms of Use".

Suggestion needed.

**Comment by BrandonBalala** [comment]
This doesn't really matter, just to make it look professional but I guess you can just link to Terms of Use page
