### ISSUE TITLE
White text in white buttons

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#216]
The text inside of white buttons is not visible because it is white 🐞
<img width="129" alt="screen shot 2017-11-16 at 10 33 38 pm" src="https://user-images.githubusercontent.com/16027312/32928076-379bd250-cb1e-11e7-8ecb-458d16168c5c.png">
<img width="127" alt="screen shot 2017-11-16 at 10 33 41 pm" src="https://user-images.githubusercontent.com/16027312/32928077-37aa9d94-cb1e-11e7-9996-db494a88a02e.png">

**Comment by monnyy** [comment]
![23660413_1687565507962921_1766279483_o](https://user-images.githubusercontent.com/25891267/32928774-b63ec1a0-cb21-11e7-9c98-1cd316835777.jpg)


![23732333_1687565497962922_1467277820_o](https://user-images.githubusercontent.com/25891267/32928788-c85e2740-cb21-11e7-8949-8e9aab1a2415.jpg)
