### ISSUE TITLE
Navbar changes

### ISSUE THREAD

**Issue by laurie-y** [classifiedz/classifiedz.github.io#22]
- [ ] Remove "My Cart" (user won't be buying in bulk like on Amazon)
- [ ] Format the user dropdown

**Comment by neqqash** [comment]
the navbar seems perfect to me, i was thinking of having a logo for our website, any suggestions for that?

**Comment by laurie-y** [comment]
The navbar itself is fine, it's just the content that I think needs to be changed.

The My Cart option can be kept(but relocated) if we plan on allowing the user to purchase multiple things at once. The issue with this is that for each item that the user wants, they have to get in contact with seller before making a transaction. If our site was geared towards mass producers where they have a stock of the product they're selling then the buyer could add things from multiple sellers into their cart without worrying about whether the item is still being sold or not.

Unless I've misunderstood, I think our sight is more closely related to Kijiji than Amazon?

As for the format of the user dropdown, I meant the aesthetics of it because it's currently invisible unless you hover over it. It's also not properly aligned.
