### ISSUE TITLE
Dropdown for registered/logged in user

### ISSUE THREAD

**Issue by laurie-y** [classifiedz/classifiedz.github.io#23]
##  Dropdown Should Contain: 
- [ ] Your Store        
- [ ] Post an Ad
- [ ] Logout

**Comment by Swallow666** [comment]
so we gonna delete and add something of navbar to those users after login.

**Comment by Swallow666** [comment]
I have an idea to change this better, when users didn't registered yet click 'your store' button, the page jump to login page so that they can login or register, and if they already registered --->'your store' .

**Comment by Swallow666** [comment]
Since this issue has been solved, let us close this one.
