### ISSUE TITLE
should Login/register be the first thing the user does when accessed to the website

### ISSUE THREAD

**Issue by neqqash** [classifiedz/classifiedz.github.io#24]
As stated before, should we start the site off by making users either register or login and then be directed to the home page of the e-commerce website?

**Comment by Swallow666** [comment]
I don't think so because if users must register or login before they visit our homepage, then they will lose interest and feel bad about this. We should make it just like 'letgo', users can choose either register or not after visiting our homepage.

**Comment by BrandonBalala** [comment]
^ I agree with @Swallow666

**Comment by laurie-y** [comment]
I also agree with @Swallow666 

User's will be put off by the fact that they have to make an account to see what's being sold. If nothing interests them after they've made an account then they'll have registered for nothing.

**Comment by neqqash** [comment]
sounds good, i think we all agree on not doing that.
