### ISSUE TITLE
Fix homepage image bug

### ISSUE THREAD

**Issue by BrandonBalala** [classifiedz/classifiedz.github.io#26]
Images on homepage are not displaying

**Comment by Swallow666** [comment]
On my computer, it displays on classified.xyz 
On http://127.0.0.1:8000, it shows card image cap. 
Yours the same?@BrandonBalala

**Comment by kevcamel** [comment]
@Swallow666 mine shows the same **card image cap**, we need to change the reference to  
- src="{{ asset('img/img-name.png') }}"
@BrandonBalala can you confirm?
