### ISSUE TITLE
Classifiedz.xyz did not change after merge things into master

### ISSUE THREAD

**Issue by Swallow666** [classifiedz/classifiedz.github.io#31]
This is a quick question, after merging pull request #28 , our website classifiedz.xyz seems not change at all , maybe there is something else I forgot, anyone can tell me?

**Comment by kevcamel** [comment]
@Swallow666 you did not forget anything. Right now we have our code sitting in two places.
1. Github  
2. Digital Ocean  

Our domain `classifiedz.xyz` is no longer linked to Github, it is now linked to Digital Ocean.  
Github serves as our git version control repository and Digital Ocean is where we are storing our actual code.
This means that when you push changes to the master branch on github they also have to manually be pushed to Digital Ocean by our backend team in order for the changes to be visible.

**Comment by Swallow666** [comment]
@kcamcam wow that's cool, I kind of understand about this stuff. This solve my question perfectly. And I will close this issue.
