### ISSUE TITLE
[User Story 3] Password and Login Security

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#48]
I would like to allow users to register and sign into the system, they should do it simply with an email. I am concerned about the security of their passwords, so we need to come up with a way to storepasswords securely on the database and some requirements to enforce medium to strong passwords.
**Estimated Hours:** 2 hours  
**Risk:** LOW
**Priority:** HIGH  
### Story points: 3

**Comment by kcamcam** [comment]
@BrandonBalala, @neqqash this issue needs to be resolved by wednesday.

**Comment by laurie-y** [comment]
## Acceptance Test
![us3](https://user-images.githubusercontent.com/31772505/32357843-e32a2396-c016-11e7-9cd7-bafce25258e1.PNG)
