### ISSUE TITLE
[Task] Functionality of the upload image button

### ISSUE THREAD

**Issue by laurie-y** [classifiedz/classifiedz.github.io#52]
The user should be able to use the upload button to upload an image of their item. There should be a size limit (file and dimensions). They should also be able to delete it and upload a different image in case they selected the wrong one.

Possibly a cropping feature?

For #9

**Comment by BrandonBalala** [comment]
@laurie-y We can keep cropping feature for Sprint 6 as G.K would say. But for know I can add a dimension check on the image?

**Comment by laurie-y** [comment]
Yeah for sure. The cropping feature doesn't need to implemented right now. The most important thing is that the user is able to upload an image and that it's not a giant file/a giant image
