### ISSUE TITLE
Registered account cannot login

### ISSUE THREAD

**Issue by Swallow666** [classifiedz/classifiedz.github.io#65]
When I login with my registered account, it shows "These credentials do not match our records." We have to figure out why this happened.

**Comment by BrandonBalala** [comment]
@Swallow666 Ahh sorry that is my fault.  When I make changes to database schema, I run php artisan migrate:refresh --seed. And this deletes all the tables and recreates them, hence why you can't login with the old credentials.

**Comment by Swallow666** [comment]
Oh ok got it, I will close this issue.
