### ISSUE TITLE
[User Story 1] Register Page

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#8]
## To Do:

- [ ] Create a new **Register** page
- [ ] Full Name
- [ ] Email
- [ ] Password
- [ ] Confirm Password
- [ ] Javascript **validation** for the input fields, i.e., only characters for name fields, only numbers for phone numbers etc... 

Will be on the same page as the login #7

**Comment by laurie-y** [comment]
## Acceptance Test
![us1](https://user-images.githubusercontent.com/31772505/32357778-292bee84-c016-11e7-8dc6-e2b07703fa83.PNG)
