### ISSUE TITLE
[Task] Functioning edit form

### ISSUE THREAD

**Issue by laurie-y** [classifiedz/classifiedz.github.io#80]
The user should be able to successfully edit their information and the new information should appear on their profile.

For user story #71

**Comment by Swallow666** [comment]
Need help for this task, I don't know how to change profile appeared by clicking on submit button in edit_profile_page. Should this be solved in php?

**Comment by Swallow666** [comment]
When I changed custom value in database, the local page didn't change, anything I missed?
@BrandonBalala

**Comment by BrandonBalala** [comment]
@Swallow666 You need to refresh page for it to show up changes

**Comment by BrandonBalala** [comment]
Does anyone currently have the edit form ready in frontend so I can implement the backend? Send me the name of the branch you are working on with all the latest changes

**Comment by Swallow666** [comment]
@BrandonBalala branch edit_profile_content

**Comment by Swallow666** [comment]
@BrandonBalala login--profile--edit profile, and then when changes profile, new profile should appear at profile page
